// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function Connections() {
  return window['go']['main']['App']['Connections']();
}

export function DeletePlugin(arg1) {
  return window['go']['main']['App']['DeletePlugin'](arg1);
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function Disconnect(arg1) {
  return window['go']['main']['App']['Disconnect'](arg1);
}

export function ExportPlugin(arg1) {
  return window['go']['main']['App']['ExportPlugin'](arg1);
}

export function ImportPlugin() {
  return window['go']['main']['App']['ImportPlugin']();
}

export function ListPlugins() {
  return window['go']['main']['App']['ListPlugins']();
}

export function ListProfiles() {
  return window['go']['main']['App']['ListProfiles']();
}

export function Publish(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['Publish'](arg1, arg2, arg3, arg4, arg5);
}

export function RemoveConnection(arg1) {
  return window['go']['main']['App']['RemoveConnection'](arg1);
}

export function SavePlugin(arg1) {
  return window['go']['main']['App']['SavePlugin'](arg1);
}

export function SaveProfile(arg1) {
  return window['go']['main']['App']['SaveProfile'](arg1);
}

export function Subscribe(arg1, arg2, arg3) {
  return window['go']['main']['App']['Subscribe'](arg1, arg2, arg3);
}

export function Unsubscribe(arg1, arg2) {
  return window['go']['main']['App']['Unsubscribe'](arg1, arg2);
}

export function Version() {
  return window['go']['main']['App']['Version']();
}
