// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {profiles} from '../models';

export function Connect(arg1:profiles.ConnectionProfile):Promise<void>;

export function DeleteProfile(arg1:string):Promise<void>;

export function Disconnect():Promise<void>;

export function ListProfiles():Promise<Array<profiles.ConnectionProfile>>;

export function Publish(arg1:string,arg2:string,arg3:number,arg4:boolean):Promise<void>;

export function SaveProfile(arg1:profiles.ConnectionProfile):Promise<profiles.ConnectionProfile>;

export function Subscribe(arg1:string,arg2:number):Promise<void>;

export function Unsubscribe(arg1:string):Promise<void>;
