// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function ListProfiles() {
  return window['go']['main']['App']['ListProfiles']();
}

export function Publish(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Publish'](arg1, arg2, arg3, arg4);
}

export function SaveProfile(arg1) {
  return window['go']['main']['App']['SaveProfile'](arg1);
}

export function Subscribe(arg1, arg2) {
  return window['go']['main']['App']['Subscribe'](arg1, arg2);
}

export function Unsubscribe(arg1) {
  return window['go']['main']['App']['Unsubscribe'](arg1);
}

export function Version() {
  return window['go']['main']['App']['Version']();
}
